# -*- coding: utf-8 -*-
"""8 de noviembre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RCDecV6w1eYT3yD74obzhY_ZOqhf6QYY
"""

import streamlit as st

st.title("Mi Primera Aplicación en streamlit")
st.header("Este es un encabezado")
st.subheader("Este es un subencabezado")
st.write("Esta es una introducción a Streamlit, donde exploraremos cómo construiraplicaciones interactivas. ")
